name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.92

      - name: Build for WebAssembly
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Generate wasm-bindgen output
        run: wasm-bindgen --out-dir pkg --target web target/wasm32-unknown-unknown/release/marie_gallery.wasm

      - name: Copy index.html to pkg
        run: cp index.html pkg/ && cp -r assets pkg/

      - name: Deploy to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git --work-tree=pkg add --all
          git --work-tree=pkg commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
